config/routes.rb
Portfolio::Application.routes.draw do
  root "pages#home"

  get "about" => "pages#about"

  # Project Pages
  get "frontier" => "pages#frontier"
  get "divvy" => "pages#divvy"
  get "statusphere" => "pages#statusphere"
  get "alamode" => "pages#a_la_mode"
  get "planit" => "pages#plan_it"
  get "scout" => "pages#scout"

  get "secondmarket_hub" => "pages#secondmarket_hub"
  get "secondmarket_checkout" => "pages#secondmarket_checkout"
  get "secondmarket_homepage" => "pages#secondmarket_homepage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def resume
  end

  def about
  end

  # Project Pages

  def frontier
  end

  def secondmarket_hub
  end

  def secondmarket_checkout
  end

  def secondmarket_homepage
  end

  def divvy
  end

  def statusphere
  end

  def a_la_mode
  end

  def plan_it
  end

  def scout
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def active?(path_to_check)
    "active" if current_page?(path_to_check)
  end

  def latest_commit_message
    repo = Github::Repos.new user: 'jayzed', repo: 'portfolio'
    repo.commits.all.first["commit"]["message"]
  end

  def latest_commit_date
    repo = Github::Repos.new user: 'jayzed', repo: 'portfolio'
    repo.commits.all.first["commit"]["author"]["date"].to_datetime.strftime("%m/%d/%Y")
  end

end

app/views/layouts/_footer.html.erb
<hr class="space">
<footer class="container">
  <hr>
  
  <div class="pull-left">
    <span class="small">Designed and built in Rails by Jordy Zagdanski, 2014</span>
  </div>

  <div class="pull-right">

    <%= mail_to "jayzed@gmail.com" do %>
      <%= fa_stacked_icon "envelope inverse", base: "circle" %>
    <% end %>

    <%= link_to "http://www.linkedin.com/profile/view?id=143149437" do %>
      <%= fa_stacked_icon "linkedin inverse", base: "circle" %> 
    <% end %>

    <%= link_to "https://github.com/jayzed", target: "_blank" do %>
      <%= fa_stacked_icon "github inverse", base: "circle" %> 
    <% end %>

  </div>
</footer>

<% if Rails.env.production? %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-31280658-1', 'jordyzagdanski.com');
  ga('send', 'pageview');

  </script>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "JORDY ZAGDANSKI", root_path, class: "navbar-brand" %>
      <div class="small hidden-xs">User Experience Designer</div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">

      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= active?(root_path) %>">
          <%= link_to "Work", root_path %>
        </li>
        <li class="<%= active?(about_path) %>">
          <%= link_to "About", about_path %>
        </li>
        <li>
          <%= link_to "Resume",  "resume2014.pdf"  %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
    <hr>
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Jordy Zagdanski - Portfolio</title>
  
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/a_la_mode.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>à la mode</h1>
    <p>à la mode is a digital magazine created specifically for the iPad</p>
    <hr class="space">
    <%= image_tag "alamode-cover.png", class: "img-responsive" %>
    <hr class="space">

    <h2>Selected Process</h2>
    <h3>Learning the landscape</h3>
    <p>
      The first stage was to conduct a competitive analysis of the eMagazine space, and more specifically to look
       at current eMagazines that are food-related. We found that many current eMagazines out there had extremely 
       cluttered layouts, which is something that we wanted to avoid.
    </p>

    <h3>Determining the Target Users</h3>
    <p>
      To help understand who we were designing for, we created 2 personas. Deborah knows how to cook, but she is not very technology 
      savvy. Our second persona on the other hand is tech-savvy, but needs help learning how to cook. We wanted our app to cater 
      to both types of people.
    </p>
    <hr class="space">

    <%= image_tag "alamode-persona.png", class: "img-responsive" %>

    <h3>Creating a Design Language</h3>
    <p>
      We created a moodboard to help understand how we wanted the magazine to feel. 
      It was extremely helpful in getting to our end color pallette.
    </p>

    <hr class="space">
    <%= image_tag "alamode-moodboard.png", class: "img-responsive" %>

    <h3>Iteration to the Final Design</h3>
    <p>
      We iterated on our designs a number of times, starting with paper sketches of different layouts then moving to digital versions. 
    </p>

    <%= image_tag "alamode-outline.png", class: "img-responsive" %>
    <hr class="space">
    <%= image_tag "alamode-page.png", class: "img-responsive" %>


    <hr class="space">
    <div class="small">
      <h5><strong>Project Details</strong></h5>
      <div>Date: Fall 2011</div>
      <div>Class: Interaction Design Fundamentals</div>
      <div>Team: Aditya Gujaran, Kyle Libby, Kelsey Lee</div>
      <div>Skills: Visual Design, Typography</div>
    </div>

  </div>
</div>

app/views/pages/about.html.erb
<div class="row">
  <div class="col-sm-9">

    <p>Hey I'm Jordy.</p>
    <p>I'm a UX designer working at <%= link_to "SecondMarket", "http://secondmarket.com" %> in NYC.</p>
    <p> I was born and raised in Toronto, Canada. Just before living in NYC I graduated in August 2012 with a Masters degree in Human-Computer Interaction from Carnegie Mellon University.</p>
    <p>I enjoy working on the whole UX process from User Research to Prototyping and Usability Testing and am always looking to learn.</p>
    <p>Feel free to <%= mail_to "jayzed@gmail.com", "email me" %> or connect with me on <%= link_to "LinkedIn", "http://www.linkedin.com/profile/view?id=143149437" %>.</p>

    <h3>About this portfolio</h3>
    <p>
      This portfolio was built by me in Ruby on Rails <%= link_to "(Github Project)", "https://github.com/jayzed/portfolio" %> and deployed using <%= link_to "Heroku", "http://www.heroku.com" %>.
      It uses the responsive <%= link_to "Bootstrap", "http://www.getbootstrap.com" %> framework, <%= link_to "Font Awesome", "http://fortawesome.github.io/Font-Awesome/" %>,
      and <%= link_to "Sass", "http://sass-lang.com/" %>.

    </p>
 
<!-- 
    <div>Most Recent Commit: <%= latest_commit_message %></div>
    <div>Commit Date: <%= latest_commit_date %></div>

 -->  </div>

  <div class="col-sm-3">
    <%= image_tag "me.jpg", class: "img-responsive" %>
  </div>

</div>

app/views/pages/divvy.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>Divvy</h1>
    <p>A mobile application to help parents manage their kids carpool schedules, and also gives the parents security that their child arrived safely.</p>
    
    <h2>Selected Process</h2>
    <p>
      We began the discovery process by conducting interviews with a couple of parents and found that managing carpool schedules is a difficult task. 
      Parents wanted more information about where their kids are, but did not want to be obtrusive.
    </p>

    <hr class="space">
    <%= image_tag "divvy-paper-prototypes.png", class: "img-responsive" %>
    <hr class="space">

    <h3>Wireframing and Iteration</h3>
    <p>
      With all that in mind, we came up with preliminary wireframes on a whiteboard, then transferred it to a paper prototype. 
      We then conducted think-aloud studies on the paper prototype to see where we could still improve. 
      The design was then iterated upon a number of times, both to increase usability and enhance the visual design.
      We began with a paper prototype, moved to an interactive prototype in Axure, and then did a number of iterations in Photoshop before arriving at the final design. 
    </p>

    <%= image_tag "divvy-evolution.png", class: "img-responsive" %>
    <hr class="space">
    
    <div class=" small">
      <h5><strong>Project Details</strong></h5>
      <div>Date: Spring 2012</div>
      <div>Class: Interaction Design Studio</div>
      <div>Team: Linda Le, Nir Rachmel</div>
      <div>Skills: Interviewing, Personas, Paper Prototyping, Think-Aloud Testing, Interaction Design, Wireframing </div>
    </div>


  </div>
</div>

app/views/pages/frontier.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>Frontier</h1>

    <hr class="space">
    <p>This was the capstone project for my Masters degree. Our team worked with our clients from Bank of America to investigate interactions and behaviors within households to see where Bank of America could translate and expand their offerings in order to design a collaborative, multi-device television experience.</p>
    
    <p>During the Spring semester we conducted extensive user research and analysis, and we used that data in the summer semester to design a high fidelity prototype.</p>
    
    <p>The details of our research findings and the final design are covered by a non-disclosure agreement.</p>

    <%= link_to "Project Website", "http://www.hcii.cmu.edu/M-HCI/2012/frontier/", class: "btn btn-default" %>

    <hr class="space">
    <%= image_tag "frontier-affinity.jpg", class: "img-responsive" %>
    <hr class="space">
    <%= image_tag "frontier-analytical.png", class: "img-responsive center-block" %>
    <hr class="space">
    <%= image_tag "frontier-field.png", class: "img-responsive center-block" %>
    <hr class="space">

    <div class="small">
      <h5><strong>Project Details</strong></h5>
      <div>Date: Spring - Summer 2012</div>
      <div>Client: Bank of America</div>
      <div>Team: Lauryn Fantano, Rohan Gaikwad, Almas Tuyakbayev, Ying Zhang</div>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<div class="well">
  <h2>Welcome!</h2>
  <p>Below you will find projects that I have worked on. <%= link_to "Learn more about me", about_path %> or <%= mail_to "jayzed@gmail.com", "email me" %> if you want to get in touch.</p>
</div>

<div class="row">
  

  <div class="portfolio-item">
    <%= link_to image_tag("checkout-logo.png", class: "img-responsive"), secondmarket_checkout_path %>
    <%= link_to "SecondMarket Checkout", secondmarket_checkout_path, class: 'portfolio-item-title' %>
    <div class="portfolio-item-description">Making investing easier</div>
  </div>

  <div class="portfolio-item">
    <%= link_to image_tag("homepage-logo.png", class: "img-responsive"), secondmarket_homepage_path %>
    <%= link_to "SecondMarket Homepage", secondmarket_homepage_path, class: 'portfolio-item-title' %>
    <div class="portfolio-item-description">Redesigning the homepage</div>
  </div>

  <div class="portfolio-item">
    <%= link_to image_tag("hub-logo.png", class: "img-responsive"), secondmarket_hub_path %>
    <%= link_to "SecondMarket Hub", secondmarket_hub_path, class: 'portfolio-item-title' %>
    <div class="portfolio-item-description">Stakeholder communication for funds and companies</div>
  </div>

</div>

<div class="row">
  <div class="portfolio-item">
    <%= link_to image_tag("frontier-logo.png", class: "img-responsive"), frontier_path %>
    <%= link_to "Frontier", frontier_path, class: 'portfolio-item-title' %>
    <div class="portfolio-item-description">Bank of America Capstone Project</div>
  </div>


  <div class="portfolio-item">
    <%= link_to image_tag("divvy-logo.png", class: "img-responsive"), divvy_path %>
    <%= link_to "Divvy", divvy_path, class: 'portfolio-item-title' %>
    <div class="portfolio-item-description">iPhone App for Carpools</div>
  </div>

  <div class="portfolio-item">
    <%= link_to image_tag("statusphere-logo.png", class: "img-responsive"), statusphere_path %>
    <%= link_to "Statusphere", statusphere_path, class: 'portfolio-item-title' %>
    <div class="portfolio-item-description">Colorful orbs to display your status in a coffee shop</div>
  </div>

</div>

<div class="row">
   <div class="portfolio-item">
    <%= link_to image_tag("scout-logo.png", class: "img-responsive"), scout_path %>
    <%= link_to "Scout", scout_path, class: 'portfolio-item-title' %>
    <div class="portfolio-item-description">People discovery application for conferences</div>
  </div>

  <div class="portfolio-item">
    <%= link_to image_tag("alamode-logo.png", class: "img-responsive"), alamode_path %>
    <%= link_to "à la mode", alamode_path, class: 'portfolio-item-title' %>
    <div class="portfolio-item-description">Desert Magazine</div>
  </div>

  <div class="portfolio-item">
    <%= link_to image_tag("planit-logo.png", class: "img-responsive"), planit_path %>
    <%= link_to "Plan it", planit_path, class: 'portfolio-item-title' %>
    <div class="portfolio-item-description">Dinner Planning Application</div>
  </div>

</div>

app/views/pages/plan_it.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>Plan it</h1>
    <p>
      Plan-It is an application to help plan dinner menus. It was an individual project designed to practice 
      various HCI methodologies.
    </p>

    <h2>Selected Process</h2>
    <h3>Research & Synthesis</h3>
    <p>
      I conducted Contextual Inquiries with 3 people who were experts at planning meals to see how the process 
      is done and where the breakdowns are. One major finding was that expert meal planners start planning with 
      a meal structure in mind while less experienced people do not. Some breakdowns included not knowing the 
      right quantity of food to make, and forgetting ingredients when going to the store.
    </p>

    <%= image_tag "planit-affinity.jpg", class: "img-responsive" %>
    
    <h3>Visualizing a Solution</h3>
    <p>
      Before making the interactive prototype, I created a storyboard to show the scenario of use where 
      the app would be used. This was helpful to begin visualizing how the prototype would look. 
    </p>

    <%= image_tag "planit-storyboard.jpg", class: "img-responsive" %>
    <hr class="space">
    
    <h3>Flex Prototype</h3>
    <p>
      I then created an interactive prototype in Flex to test the idea, and also conducted several Think-Aloud studies to improve the overall usability.
    </p>

    <%= image_tag "planit-screenshot.jpg", class: "img-responsive" %>

    <div class=" small">
      <h5><strong>Project Details</strong></h5>
      <div>Date: Fall 2011</div>
      <div>Class: User-Centered Design & Evaluation</div>
      <div>Skills: Competitive Analysis, Contextual Inquiries, Affinity Diagramming, Think-Aloud Testing, Storyboarding, Interaction Design</div>
    </div>

  </div>
</div>

app/views/pages/scout.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>Scout</h1>
    <p>A people discovery application for professionals at meetings and conferences.</p>
    
    <h2>Selected Process</h2>    
    <p>
      The goal of this class was slightly different than others in the MHCI program. While most classes were focused on 
      specifically user-centered design, this one was focused on how to identify and create value within an ecosystem.
      The main motivation behind the class was by assessing potential value first, you are more likely to create something
      that people would want to use and would pay for.
    </p>

    <h3>Brainstorming</h3>
    <p>
      We spent a lot of time brainstorming different areas to focus on. At the time we were all looking for jobs
      and weren't having great experiences at job fairs so we decided to focus on that space. We created a value diagram to see how money flows and where our app would fit in.
      We feld that there was an opportunity to help candidates find jobs at job fairs.
    </p>

    <%= image_tag "scout-value-diagram.png", class: "img-responsive" %>
    <hr class="space">

    <h3>User Research</h3>
    <p>
      From our experience we knew that job fairs are inefficient because it's usually very busy and it's not always 
      clear exactly what companies are looking for.
      We interviewed recruiters and students at a job fair to better understand what problems they were having. 
    </p>

    <p>
      From recruiters we found an interesting dichotomy at job fairs; One one hand the startups had trouble attracting students because 
      they are not as well known, and on the other hand some of the large companies were only looking for interns and not full time employees.
      From students we learned that they wanted more information; it was awkward approaching unknown companies, and recruiters were not knowledgeable about every position.
      From this research we found that there was an opportunity in the space to help connect students and companies, and created personas
      to exemplify our target users.
    </p>

    <h3>Competitive Analysis</h3>
    <p>
      To better understand the products that were currently available, we conducted a competitive analysis to see where potential gaps were.
    </p>

    <%= image_tag "scout-competitive-analysis.png", class: "img-responsive" %>
    <hr class="space">
    <%= image_tag "scout-opportunity.png", class: "img-responsive" %>
    <hr class="space">
    <%= image_tag "scout-persona.png", class: "img-responsive" %>

    <h3>Wireframing</h3>
    <p>
      We took all of our research findings and created wireframes of the potential mobile app. We envisioned an app that you could use at job fairs
      and conferences where if you login and register, it would pull information from LinkedIn about all the people who are at the conference, and then
      show you the people nearby with their background. This way job seekers would have more information to start a conversation and would know more information
      about who at the job fair is looking for what in particular.
    </p>

    <%= image_tag "scout-screenshot.png", class: "img-responsive" %>

    <hr class="space">
    <div class="small">
      <h5><strong>Project Details</strong></h5>
      <div>Date: Spring 2012</div>
      <div>Client: Designing Mobile Services</div>
      <div>Team: Brittany Hamtil, Faye Han, Linda Le and Eli Rosen </div>
      <div>Skills: User Research, Value Diagrams, Competitive Analysis, Personas, Scenarios, Use Cases, Wireframing</div>
    </div>

  </div>
</div>

app/views/pages/secondmarket_checkout.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>SecondMarket Checkout</h1>
    <%= link_to "SecondMarket", "https://www.secondmarket.com", class: "small" %>
    
    <h2>Background</h2>
    <p>
      Investment documents are complicated. They are commonly dozens of pages long and written in legalese.
      SecondMarket noticed this problem when they created a fund for accredited investors to invest in Facebook before the IPO. The error rate while filling out
      the documents was an astonishing <strong>300%</strong> - meaning the document had to go back and forth 3 times on average between SecondMarket
      and the investor before being correctly completed. This completely offline process was extremely inefficient, time consuming and costly.
    </p>

    <h2>My Role</h2>
    <p>
      Since April 2013 I have been the lead UX designer on this product and have done all aspects of the UX process. 
      For example, talking to customers to uncover their pain points, working with product managers and business stakeholders
      to determine priorities and potential features, creating HTML prototypes, and working closely with the engineers
      while features were being implemented.
    </p>

    <h2>The Product</h2>
    <p>
      SecondMarket Checkout is an online workflow for investors to make it much easier to fill out investment documents. 
      Investors complete a wizard where they enter all of their necessary information which automatically populates a document for them to sign.
      In 2013 alone, thousands of orders were created and processed online.
    </p>

    <hr class="space">
    <div id="checkout-carousel" class="carousel slide" data-ride="carousel" data-interval="false">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#checkout-carousel" data-slide-to="0" class="active"></li>
        <li data-target="#checkout-carousel" data-slide-to="1"></li>
        <li data-target="#checkout-carousel" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag "checkout-amount.png" %>
        </div>
        <div class="item">
          <%= image_tag "checkout-personal-info.png" %>
        </div>

        <div class="item">
          <%= image_tag "checkout-bank-info.png" %>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#checkout-carousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#checkout-carousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>
    <hr class="space">

    <p>
      There are also multiple views for different stakeholders:
    </p>

    <ul>
      <li>An Investor view to complete the investment flow and sign subscription documents</li>
      <li>An Internal view for SecondMarket employees to manage orders going through the system</li>
      <li>"Observer View" for fund administrators to see the funnel of investors through the flow.</li>
    </ul>

    <p> 
      All of these different views need to be considered when making adjustments
      to ensure the views achieve the goal of each persona.
    </p>


    <h2>Key Takeaways</h2>
    <hr class="space">
    <ul>
      <li>
        <strong>Focus on goals and success metrics to make data-driven decisions</strong>
        <p>
          All elements on a page should have a purpose.
          Once the sucess metrics are met then you can look at the data to determine if a design is successful.
        </p>
      </li>

      <li>
        <strong>Need to consider both the details and the whole picture when working on a product</strong>
        <p>
          Even when adjusting something as small as a label, each piece of the flow needs to be thought about in the overall context.
          How does the use user get to this screen? What have they already seen? What is the next step?
        </p>
      </li>

      <li>
        <strong>Need to think about both first time users and repeat users</strong>
        <p>
          For this product we have many people who invested multiple times. Once all of their information is in the system we tried to make it as easy as possible to 
          invest a second time without having to input any additional information. 
        </p>
      </li>

      <li>
        <strong>Need to understand both user needs and business processes</strong>
        <p>
          While our main flow was focused on investors, the product would be unsuccessful if the SecondMarket team struggled to manage the orders. We spent
          a lot of time optimizing the views for SecondMarket users, increasing effeciency so that hundreds of investors could be managed by a single person. 
        </p>
      </li>

      <li>
        <strong>Support Tickets = Free Feedback</strong>
        <p>
          Support tickets are extremely valuable pieces of data. If someone is taking the time to tell you there is a problem or they don't understand anything,
          it's probably a good indication where improvements can be made.
        </p>
      </li>

    </ul>
    
  </div>
</div>

app/views/pages/secondmarket_hub.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>SecondMarket Hub</h1>
    <%= link_to "SecondMarket", "https://www.secondmarket.com", class: "small" %>
    
    <h2>Background</h2>
    <p>
      While building the <%= link_to "checkout product", secondmarket_checkout_path %>, we noticed that companies and funds wanted an easier way 
      more communicate to their investors to let them know how things were going. This communication includes both updates and documents.
    </p>

    <h2>My Role</h2>
    <p>
      I have been the lead UX designer on this product from April 2013. I was involved from the very initial stages
      of product discovery to the ongoing research, prototyping, and usability testing.
      The hub is completely responsive and utilizes the bootstrap framework.
    </p>
    

    <h2>The Product</h2>
    <p>
      The SecondMarket Hub is a self-serve product for companies and funds to distribute updates and documents to their investors.
      It includes a blog-style updates page for users to send updates that can be specific to a group of people, and a way
      to bulk-upload documents.
    </p>

    <hr class="space">

    <div id="hub-carousel" class="carousel slide" data-ride="carousel" data-interval="false">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#hub-carousel" data-slide-to="0" class="active"></li>
        <li data-target="#hub-carousel" data-slide-to="1"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag "hub-first.jpg", class: "img-responsive" %>

          <div class="carousel-caption">
            First Drawing
          </div>
        </div>
        <div class="item">
          <%= image_tag "hub-updates.png", class: "img-responsive" %>

          <div class="carousel-caption">
            Current Version
          </div>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#hub-carousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#hub-carousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>

    <hr class="space">


    <h2>Key Takeaway</h2>
    <hr class="space">
    <ul>
      <li>
        <strong>Words Matter</strong>
        <p>
          Users want to make sure that information (especially sensitive information), is destributed to the right people.
          Having clear text helps the user feel more secure that they aren't making a mistake. 
        </p>
      </li>
    </ul>    


  </div>
</div>